services:
  SaaSFormation\Framework\MongoDBBasedReadModel\Infrastructure\ReadModel\MongoDBClientProvider:
    public: true
    arguments:
      $envVarsManager: '@default_env_vars_manager'
  SaaSFormation\Framework\MongoDBBasedReadModel\Infrastructure\ReadModel\MongoDBBasedReadModelRepository:
    arguments:
      $mongoDBClientProvider: '@SaaSFormation\Framework\MongoDBBasedReadModel\Infrastructure\ReadModel\MongoDBClientProvider'
      $logger: '@default_logger'